[package]
name = "map_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
image = { version = "0.25", default-features = false, features = ["png"] }
